# Generated by Django 2.0.7 on 2018-11-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('endereço', models.CharField(max_length=128, verbose_name='Endereço')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
            },
        ),
        migrations.CreateModel(
            name='DocumentoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('data_cadastro', models.DateField(verbose_name='Data Documento')),
                ('autor', models.CharField(max_length=128, verbose_name='Autor')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_skyblue.Condominio')),
            ],
            options={
                'verbose_name': 'Documento Institucional',
                'verbose_name_plural': 'Documentos Institucionais',
            },
        ),
    ]
